# Generated by Django 5.2.8 on 2025-11-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_publicacion', models.DateField()),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
